spring.application.name=SpringSecurity

# Database URL
spring.datasource.url=${DB_URL}

# MySQL username
spring.datasource.username=${DB_USERNAME}

# MySQL password
spring.datasource.password=${DB_PASSWORD}

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=create

# Show SQL queries
spring.jpa.show-sql=true

# SQL formatting
spring.jpa.properties.hibernate.format_sql=true

# MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Always run SQL initialization scripts
spring.sql.init.mode=always
 

# Execute data.sql after Hibernate creates/updates the tables
spring.jpa.defer-datasource-initialization=true

server.servlet.context-path=/api/v1

#Security Config
#spring.security.user.name=uday        // will do via UserDetailsSerivice in WebConfig
#spring.security.user.password=pass

jwt.secretKey=${JWT_TOKEN}

logging.level.org.springframework.security=DEBUG

#spring.security.oauth2.client.registration.google.client-id=aslfjdlas
#spring.security.oauth2.client.registration.google.client-secret=
#// here u need to write the entire same line again and again due to the Syntax so here is the alternative way to simplify this by yml file